---
- name: "Init HAProxy"
  hosts: loadbalancers
  gather_facts: true
  become: true
  tags:
    - init
  pre_tasks:
    - name: Update repositories cache
      ansible.builtin.apt:
        update_cache: true
  roles:
    - role: geerlingguy.docker
      docker_apt_arch: "amd64"
      docker_install_compose: true
      docker_compose_version: "v2.6.1"
      docker_compose_path: /usr/local/bin/docker-compose
- name: "Install HAProxy"
  hosts: loadbalancers
  gather_facts: true
  become: true
  tags:
    - install      
  tasks:
    - name: "Install certbot"
      ansible.builtin.include_role:
        name: hopr.certbot
    - name: "Include and setup HA Proxy"
      ansible.builtin.include_role:
        name: hopr.haproxy        
- name: "Setup HAProxy"
  hosts: loadbalancers
  gather_facts: true
  become: true
  tags:
    - setup
  tasks:
    - name: "Install certificates"
      ansible.builtin.include_role:
        name: hopr.certbot
        tasks_from: add_certificate
      vars:
        certificate_domain_name: "{{ item.domain_name }}"
        certificate_email: "{{ item.email }}"
      with_items:
        - domain_name: "{{ gnosis_domain_name }}"
          email: "acme@hoprnet.org"
        - domain_name: "{{ goerli_domain_name }}"
          email: "acme@hoprnet.org"
    - name: "Add HAProxy backends"
      ansible.builtin.include_role:
        name: hopr.haproxy
        tasks_from: add_backend
      vars:
        domain_name: "{{ item.domain_name }}"
        backend_port: "{{ item.backend_port }}"
        backend_hosts: "{{ item.backend_hosts }}"
      with_items:
        - domain_name: "{{ gnosis_domain_name }}"
          backend_port: "{{ gnosis_backend_port }}"
          backend_hosts: "{{ gnosis_backend_hosts }}"
        - domain_name: "{{ goerli_domain_name }}"
          backend_port: "{{ goerli_backend_port }}"
          backend_hosts: "{{ goerli_backend_hosts }}"        
